### ISSUE TITLE
Cluster config needs to be translated into another format

### ISSUE THREAD

**Issue by jsafrane** [IBM/ibm-vpc-block-csi-driver-operator#7]
Right now, OpenShift creates a ConfigMap openshift-config/cloud-provider-config with this content:

```
data:
  config: |+
    [global]
    version = 1.1.0
    [kubernetes]
    config-file = ""
    [provider]
    accountID = <censored>
    clusterID = dhost-1-ljhhm
    cluster-default-provider = g2
    region = us-east
    g2Credentials = /etc/vpc/ibmcloud_api_key
    g2VpcName = dhost-1-ljhhm-vpc
    g2workerServiceAccountID = <censored>
```

In addition, cloud-credentials-operator provides a Secret with this content:
https://github.com/openshift/cloud-credential-operator/blob/fb3717b67a5295b2bdace01b46b3fd39b93b19b6/pkg/cmd/provisioning/ibmcloud/service_id.go#L24-L34
(the Secret namespace/name is configurable, let's assume it's `openshift-cluster-csi-drivers/ibm-vpc-cloud-credentials`).

The CSI driver operator needs to translate these two into something that the CSI driver understands and provide it to the driver (as env. vars / secret volume).

**Comment by jsafrane** [comment]
Prior art: in Manila CSI driver operator we translate a Secret provided by cloud-credentials-operator (CCO) into a format understood by the CSI driver. We created a completely new library-go style controller. It watches all secrets in the operator namespace, so if the source CCO Secret changes, the controller will update the destination secret.
https://github.com/openshift/csi-driver-manila-operator/tree/bd89cdea66e97a48188ee752cdc092840f56ee06/pkg/controllers/secret
The code should be pretty understandable here.

The VPC CSI driver operator should do something very similar - instead of translating a CCO Secret to another Secret, it should translate CCO Secret + ConfigMap (from openshift-config namespace!) into a Secret.
* It should watch both CCO Secret (in the operator namespace) and ConfigMap (in openshift-config namespace), which is configured in `NewSecretSyncController`.
  * Feel free to watch *all* Secrets in the operator NS and all ConfigMaps in openshift-config, no need to optimize it for now.
* In `sync()` it should get both CCO Secret+ConfigMap, do the translation and write the new Secret.
  * `sync()` is called when any watched object changes, so you should get all source ConfigMap / Secrets changes (and much more, but again, don't optimize too early)
* Keep it simple.

The final CSI driver Deployment / DaemonSet should then use the "translated" Secret and give it to the driver.

**Comment by gayathrimenath-ibm** [comment]
added changes and merged to master
